name: Deploy to VPS

on:
  push:
    branches:
      - main  # Pastikan ini sesuai nama branch utama kamu (main atau master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # 1. Masuk ke folder project
          cd ~/GRETIVA-COMPRO
          
          # 2. Reset paksa agar sama persis dengan GitHub (Menghindari konflik)
          git fetch origin
          git reset --hard origin/main
          
          # 3. Install ulang dependensi (jaga-jaga ada library baru)
          npm install
          
          # 4. Build Project
          npm run build
          
          # 5. Restart Nginx (Opsional, biasanya tidak perlu kalau cuma file statis, tapi bagus untuk memastikan cache bersih)
          sudo systemctl reload nginx
          
          echo "ðŸš€ Deployment Berhasil!"